[mypy]
# Ignora los errores relacionados con importaciones faltantes.
ignore_missing_imports = True 

# Revisa el cuerpo de TODAS las funciones, incluso las que no tienen 
# anotaciones de tipo. Es una buena forma de empezar.
; check_untyped_defs = True

# No permite definir funciones sin anotaciones de tipo. 
; disallow_untyped_defs = True

# Advierte si una función puede devolver 'Any'
; warn_return_any = True

# No permite el uso implícito del tipo 'Any'. Obliga a ser explícito.
; disallow_implicit_any = True

;! Revisar esto
# Esta única línea habilita un conjunto de chequeos de alta calidad,
# incluyendo el equivalente a 'disallow_implicit_any' y muchos otros.
# Es la práctica recomendada para nuevos proyectos.
; strict = True

;! Viejo:
; [mypy]
; ;! Ignora los errores relacionados con importaciones faltantes.
; ignore_missing_imports = True 

; ; ;! Advierte sobre opciones de configuración no utilizadas.
; warn_unused_configs = False

; ;! Usar bases de paquetes explícitas para evitar conflictos de módulos
; explicit_package_bases = True