[mypy]
;! Ignora los errores relacionados con importaciones faltantes.
ignore_missing_imports = True 

;! Advierte sobre opciones de configuración no utilizadas.
warn_unused_configs = False

;! Usar bases de paquetes explícitas para evitar conflictos de módulos
explicit_package_bases = True